/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#121316",
        "muted-slate": "#6B7280",
        "surface-container-highest": "#343538",
        "tertiary": "#bfcdff",
        "on-surface": "#e3e2e6",
        "on-primary": "#3c2f00",
        "on-secondary-fixed": "#002114",
        "on-secondary": "#003825",
        "outline": "#99907c",
        "border-low": "#2D3748",
        "on-background": "#e3e2e6",
        "secondary-fixed": "#85f8c4",
        "tertiary-fixed": "#dbe1ff",
        "outline-variant": "#4d4635",
        "surface-container-lowest": "#0d0e11",
        "secondary": "#68dba9",
        "secondary-container": "#25a475",
        "inverse-on-surface": "#303034",
        "on-error": "#690005",
        "primary-fixed": "#ffe088",
        "on-error-container": "#ffdad6",
        "surface-bright": "#38393c",
        "tertiary-container": "#97b0ff",
        "on-tertiary-fixed": "#00174b",
        "on-tertiary-container": "#254188",
        "surface-tint": "#e9c349",
        "on-secondary-fixed-variant": "#005137",
        "tertiary-fixed-dim": "#b4c5ff",
        "surface-container": "#1f1f23",
        "primary-fixed-dim": "#e9c349",
        "on-secondary-container": "#00311f",
        "surface": "#16181D",
        "primary-container": "#d4af37",
        "error": "#ffb4ab",
        "surface-container-low": "#1b1b1f",
        "inverse-primary": "#735c00",
        "on-primary-fixed": "#241a00",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#27438a",
        "error-red": "#EF4444",
        "text-pearl": "#EAECEF",
        "on-surface-variant": "#d0c5af",
        "on-primary-fixed-variant": "#574500",
        "surface-container-high": "#292a2d",
        "inverse-surface": "#e3e2e6",
        "on-tertiary": "#082b72",
        "primary": "#f2ca50",
        "background": "#121316",
        "surface-variant": "#343538",
        "secondary-fixed-dim": "#68dba9",
        "on-primary-container": "#554300"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "0px"
      },
      spacing: {
        "margin-mobile": "16px",
        "section-gap": "120px",
        "unit": "8px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "container-max": "1440px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Syne", "sans-serif"],
        "body-lg": ["JetBrains Mono", "monospace"],
        "display": ["Syne", "sans-serif"],
        "headline-lg": ["Syne", "sans-serif"],
        "metric": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-md": ["JetBrains Mono", "monospace"],
        "headline-md": ["Syne", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display": ["80px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "headline-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "metric": ["32px", { "lineHeight": "1", "letterSpacing": "-0.02em", "fontWeight": "500" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.15em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
